name: Continuous Deployment (CD)

on:
  push:
    branches:
      - master  # Automated deployment

jobs:
  deploy:
    name: Deploy to Koyeb
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Install Koyeb CLI
        run: |
          curl -sSL https://get.koyeb.com | bash

      - name: Deploy to Koyeb
        env:
          KOYEB_API_KEY: ${{ secrets.KOYEB_API_KEY }}
        run: koyeb service redeploy my-app
