name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarcloud:
    name: Run SonarCloud analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'

      - name: Cache SonarCloud dependencies
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-sonar-

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run SonarCloud analysis
        uses: SonarSource/sonarcloud-github-action@v1
        with:
          organization: "danferdiansyah"
          token: ${{ secrets.SONAR_TOKEN }}
